"""Compatibility entry point for the Orchestrator live E2E suite.

Implementation lives in ``scripts.orchestrator_e2e``. Keep imports from this
module stable for existing script tests and ad-hoc tooling.
"""

from __future__ import annotations

from scripts.orchestrator_e2e import config as _config
from scripts.orchestrator_e2e.evaluators import (
    evaluate_p1_agent_capability_profile,
    evaluate_p1_evaluation_repair,
    evaluate_p1_rich_artifacts,
    evaluate_p2_agent_capability_profile_v2,
)
from scripts.orchestrator_e2e.runner import (
    AGENT_FALLBACK_MATRIX_PROMPT,
    AGENT_IDS,
    COMMAND_FULFILLMENT_PROMPT,
    CUSTOM_AGENT_READER_REVIEW_REPAIR_PROMPT,
    CUSTOM_AGENT_TOOLS_PROMPT,
    CYBERPUNK_QUALITY_PROMPT,
    CYBERPUNK_QUALITY_V2_PROMPT,
    DEPLOYMENT_PROMPT,
    DEPLOYMENT_REPAIR_PROMPT,
    DIALOGUE_AI_BENEFITS_RISKS_LLM_MODERATED_PROMPT,
    FULLSTACK_PROMPT,
    GROUP_CHAT_ATTRIBUTION_PROCESS_MATRIX_PROMPT,
    GROUP_DIALOGUE_DEBATE_PROMPT,
    GROUP_MEMBER_FALLBACK_REPAIR_VISIBILITY_PROMPT,
    GROUP_PROCESS_DATA_ANALYSIS_PROMPT,
    GROUP_PROCESS_DOCUMENT_STRATEGY_PROMPT,
    GROUP_PROCESS_FAILURE_READABLE_PROMPT,
    GROUP_PROCESS_WORKFLOW_DELIVERY_PROMPT,
    IM_CONTEXT_PIN_FOLLOWUP_REPAIR_PROMPT,
    ONE_CLICK_CONTAINER_DEPLOY_REPAIR_PROMPT,
    P1_AGENT_CAPABILITY_PROFILE_AGENT_IDS,
    P1_AGENT_CAPABILITY_PROFILE_PROMPT,
    P1_AGENT_CAPABILITY_PROFILE_SEED_PROMPT,
    P1_ATTRIBUTION_PROMPT,
    P1_EVALUATION_REPAIR_PROMPT,
    P1_REVIEW_THREAD_PROMPT,
    P1_RICH_ARTIFACTS_PROMPT,
    P1_WORKFLOW_PROMPT,
    P1_WORKFLOW_RUNTIME_PROMPT,
    P2_AGENT_CAPABILITY_PROFILE_V2_PROMPT,
    PRESENTATION_COLLAPSE_PROMPT,
    PURE_DIALOGUE_ROBUSTNESS_MATRIX_PROMPT,
    SERVER_COMMAND_RE,
    STATIC_PACKAGE_DEPLOY_REPAIR_MATRIX_PROMPT,
    TASK_MANAGER_PARALLEL_PROMPT,
    TASK_MANAGER_PARALLEL_V2_PROMPT,
    main,
)
from scripts.orchestrator_e2e.runner import (
    GROUP_SUBSTANTIVE_OUTPUT_MATRIX_PROMPT as GROUP_SUBSTANTIVE_OUTPUT_MATRIX_PROMPT,
)
from scripts.orchestrator_e2e.scenarios import SCENARIOS, ScenarioSpec, get_scenario

DEFAULT_CUSTOM_AGENT_TOOLS_REPORT_PATH = _config.DEFAULT_CUSTOM_AGENT_TOOLS_REPORT_PATH
DEFAULT_CUSTOM_AGENT_TOOLS_SSE_PATH = _config.DEFAULT_CUSTOM_AGENT_TOOLS_SSE_PATH
DEFAULT_AGENT_FALLBACK_MATRIX_REPORT_PATH = (
    _config.DEFAULT_AGENT_FALLBACK_MATRIX_REPORT_PATH
)
DEFAULT_AGENT_FALLBACK_MATRIX_SSE_PATH = _config.DEFAULT_AGENT_FALLBACK_MATRIX_SSE_PATH
DEFAULT_COMMAND_FULFILLMENT_BROWSER_REPORT_PATH = (
    _config.DEFAULT_COMMAND_FULFILLMENT_BROWSER_REPORT_PATH
)
DEFAULT_COMMAND_FULFILLMENT_REPORT_PATH = (
    _config.DEFAULT_COMMAND_FULFILLMENT_REPORT_PATH
)
DEFAULT_COMMAND_FULFILLMENT_SSE_PATH = _config.DEFAULT_COMMAND_FULFILLMENT_SSE_PATH
DEFAULT_CONTEXT_FOLLOWUP_BROWSER_REPORT_PATH = (
    _config.DEFAULT_CONTEXT_FOLLOWUP_BROWSER_REPORT_PATH
)
DEFAULT_CONTEXT_FOLLOWUP_REPORT_PATH = _config.DEFAULT_CONTEXT_FOLLOWUP_REPORT_PATH
DEFAULT_CONTEXT_FOLLOWUP_SSE_PATH = _config.DEFAULT_CONTEXT_FOLLOWUP_SSE_PATH
DEFAULT_PRESENTATION_MARKERS_BROWSER_REPORT_PATH = (
    _config.DEFAULT_PRESENTATION_MARKERS_BROWSER_REPORT_PATH
)
DEFAULT_PRESENTATION_MARKERS_REPORT_PATH = _config.DEFAULT_PRESENTATION_MARKERS_REPORT_PATH
DEFAULT_PRESENTATION_MARKERS_SSE_PATH = _config.DEFAULT_PRESENTATION_MARKERS_SSE_PATH
DEFAULT_GROUP_DIALOGUE_DEBATE_REPORT_PATH = (
    _config.DEFAULT_GROUP_DIALOGUE_DEBATE_REPORT_PATH
)
DEFAULT_GROUP_DIALOGUE_DEBATE_SSE_PATH = _config.DEFAULT_GROUP_DIALOGUE_DEBATE_SSE_PATH
DEFAULT_GROUP_SUBSTANTIVE_OUTPUT_MATRIX_REPORT_PATH = (
    _config.DEFAULT_GROUP_SUBSTANTIVE_OUTPUT_MATRIX_REPORT_PATH
)
DEFAULT_GROUP_SUBSTANTIVE_OUTPUT_MATRIX_SSE_PATH = (
    _config.DEFAULT_GROUP_SUBSTANTIVE_OUTPUT_MATRIX_SSE_PATH
)
DEFAULT_DEPLOYMENT_BROWSER_REPORT_PATH = _config.DEFAULT_DEPLOYMENT_BROWSER_REPORT_PATH
DEFAULT_DEPLOYMENT_REPAIR_BROWSER_REPORT_PATH = (
    _config.DEFAULT_DEPLOYMENT_REPAIR_BROWSER_REPORT_PATH
)
DEFAULT_DEPLOYMENT_REPAIR_REPORT_PATH = _config.DEFAULT_DEPLOYMENT_REPAIR_REPORT_PATH
DEFAULT_DEPLOYMENT_REPAIR_SSE_PATH = _config.DEFAULT_DEPLOYMENT_REPAIR_SSE_PATH
DEFAULT_ONE_CLICK_CONTAINER_DEPLOY_REPAIR_REPORT_PATH = (
    _config.DEFAULT_ONE_CLICK_CONTAINER_DEPLOY_REPAIR_REPORT_PATH
)
DEFAULT_ONE_CLICK_CONTAINER_DEPLOY_REPAIR_SSE_PATH = (
    _config.DEFAULT_ONE_CLICK_CONTAINER_DEPLOY_REPAIR_SSE_PATH
)
DEFAULT_DEPLOYMENT_REPORT_PATH = _config.DEFAULT_DEPLOYMENT_REPORT_PATH
DEFAULT_DEPLOYMENT_SSE_PATH = _config.DEFAULT_DEPLOYMENT_SSE_PATH
DEFAULT_FULLSTACK_BROWSER_REPORT_PATH = _config.DEFAULT_FULLSTACK_BROWSER_REPORT_PATH
DEFAULT_FULLSTACK_REPORT_PATH = _config.DEFAULT_FULLSTACK_REPORT_PATH
DEFAULT_FULLSTACK_SSE_PATH = _config.DEFAULT_FULLSTACK_SSE_PATH
DEFAULT_TASK_MANAGER_PARALLEL_BROWSER_REPORT_PATH = (
    _config.DEFAULT_TASK_MANAGER_PARALLEL_BROWSER_REPORT_PATH
)
DEFAULT_TASK_MANAGER_PARALLEL_REPORT_PATH = (
    _config.DEFAULT_TASK_MANAGER_PARALLEL_REPORT_PATH
)
DEFAULT_TASK_MANAGER_PARALLEL_SSE_PATH = _config.DEFAULT_TASK_MANAGER_PARALLEL_SSE_PATH
DEFAULT_TASK_MANAGER_PARALLEL_V2_BROWSER_REPORT_PATH = (
    _config.DEFAULT_TASK_MANAGER_PARALLEL_V2_BROWSER_REPORT_PATH
)
DEFAULT_TASK_MANAGER_PARALLEL_V2_REPORT_PATH = (
    _config.DEFAULT_TASK_MANAGER_PARALLEL_V2_REPORT_PATH
)
DEFAULT_TASK_MANAGER_PARALLEL_V2_SSE_PATH = (
    _config.DEFAULT_TASK_MANAGER_PARALLEL_V2_SSE_PATH
)
DEFAULT_CYBERPUNK_QUALITY_BROWSER_REPORT_PATH = (
    _config.DEFAULT_CYBERPUNK_QUALITY_BROWSER_REPORT_PATH
)
DEFAULT_CYBERPUNK_QUALITY_REPORT_PATH = _config.DEFAULT_CYBERPUNK_QUALITY_REPORT_PATH
DEFAULT_CYBERPUNK_QUALITY_SSE_PATH = _config.DEFAULT_CYBERPUNK_QUALITY_SSE_PATH
DEFAULT_CYBERPUNK_QUALITY_V2_BROWSER_REPORT_PATH = (
    _config.DEFAULT_CYBERPUNK_QUALITY_V2_BROWSER_REPORT_PATH
)
DEFAULT_CYBERPUNK_QUALITY_V2_REPORT_PATH = (
    _config.DEFAULT_CYBERPUNK_QUALITY_V2_REPORT_PATH
)
DEFAULT_CYBERPUNK_QUALITY_V2_SSE_PATH = _config.DEFAULT_CYBERPUNK_QUALITY_V2_SSE_PATH
DEFAULT_IM_CONTEXT_PIN_FOLLOWUP_REPAIR_BROWSER_REPORT_PATH = (
    _config.DEFAULT_IM_CONTEXT_PIN_FOLLOWUP_REPAIR_BROWSER_REPORT_PATH
)
DEFAULT_IM_CONTEXT_PIN_FOLLOWUP_REPAIR_REPORT_PATH = (
    _config.DEFAULT_IM_CONTEXT_PIN_FOLLOWUP_REPAIR_REPORT_PATH
)
DEFAULT_IM_CONTEXT_PIN_FOLLOWUP_REPAIR_SSE_PATH = (
    _config.DEFAULT_IM_CONTEXT_PIN_FOLLOWUP_REPAIR_SSE_PATH
)
DEFAULT_GROUP_CHAT_ATTRIBUTION_PROCESS_MATRIX_BROWSER_REPORT_PATH = (
    _config.DEFAULT_GROUP_CHAT_ATTRIBUTION_PROCESS_MATRIX_BROWSER_REPORT_PATH
)
DEFAULT_GROUP_CHAT_ATTRIBUTION_PROCESS_MATRIX_REPORT_PATH = (
    _config.DEFAULT_GROUP_CHAT_ATTRIBUTION_PROCESS_MATRIX_REPORT_PATH
)
DEFAULT_GROUP_CHAT_ATTRIBUTION_PROCESS_MATRIX_SSE_PATH = (
    _config.DEFAULT_GROUP_CHAT_ATTRIBUTION_PROCESS_MATRIX_SSE_PATH
)
DEFAULT_CUSTOM_AGENT_READER_REVIEW_REPAIR_BROWSER_REPORT_PATH = (
    _config.DEFAULT_CUSTOM_AGENT_READER_REVIEW_REPAIR_BROWSER_REPORT_PATH
)
DEFAULT_CUSTOM_AGENT_READER_REVIEW_REPAIR_REPORT_PATH = (
    _config.DEFAULT_CUSTOM_AGENT_READER_REVIEW_REPAIR_REPORT_PATH
)
DEFAULT_CUSTOM_AGENT_READER_REVIEW_REPAIR_SSE_PATH = (
    _config.DEFAULT_CUSTOM_AGENT_READER_REVIEW_REPAIR_SSE_PATH
)
DEFAULT_STATIC_PACKAGE_DEPLOY_REPAIR_MATRIX_BROWSER_REPORT_PATH = (
    _config.DEFAULT_STATIC_PACKAGE_DEPLOY_REPAIR_MATRIX_BROWSER_REPORT_PATH
)
DEFAULT_STATIC_PACKAGE_DEPLOY_REPAIR_MATRIX_REPORT_PATH = (
    _config.DEFAULT_STATIC_PACKAGE_DEPLOY_REPAIR_MATRIX_REPORT_PATH
)
DEFAULT_STATIC_PACKAGE_DEPLOY_REPAIR_MATRIX_SSE_PATH = (
    _config.DEFAULT_STATIC_PACKAGE_DEPLOY_REPAIR_MATRIX_SSE_PATH
)
DEFAULT_GROUP_MEMBER_FALLBACK_REPAIR_VISIBILITY_BROWSER_REPORT_PATH = (
    _config.DEFAULT_GROUP_MEMBER_FALLBACK_REPAIR_VISIBILITY_BROWSER_REPORT_PATH
)
DEFAULT_GROUP_MEMBER_FALLBACK_REPAIR_VISIBILITY_REPORT_PATH = (
    _config.DEFAULT_GROUP_MEMBER_FALLBACK_REPAIR_VISIBILITY_REPORT_PATH
)
DEFAULT_GROUP_MEMBER_FALLBACK_REPAIR_VISIBILITY_SSE_PATH = (
    _config.DEFAULT_GROUP_MEMBER_FALLBACK_REPAIR_VISIBILITY_SSE_PATH
)
DEFAULT_IM_DIALOGUE_NO_ARTIFACT_TURN_TAKING_V2_BROWSER_REPORT_PATH = (
    _config.DEFAULT_IM_DIALOGUE_NO_ARTIFACT_TURN_TAKING_V2_BROWSER_REPORT_PATH
)
DEFAULT_IM_DIALOGUE_NO_ARTIFACT_TURN_TAKING_V2_REPORT_PATH = (
    _config.DEFAULT_IM_DIALOGUE_NO_ARTIFACT_TURN_TAKING_V2_REPORT_PATH
)
DEFAULT_IM_DIALOGUE_NO_ARTIFACT_TURN_TAKING_V2_SSE_PATH = (
    _config.DEFAULT_IM_DIALOGUE_NO_ARTIFACT_TURN_TAKING_V2_SSE_PATH
)
DEFAULT_DIALOGUE_AI_BENEFITS_RISKS_LLM_MODERATED_BROWSER_REPORT_PATH = (
    _config.DEFAULT_DIALOGUE_AI_BENEFITS_RISKS_LLM_MODERATED_BROWSER_REPORT_PATH
)
DEFAULT_DIALOGUE_AI_BENEFITS_RISKS_LLM_MODERATED_REPORT_PATH = (
    _config.DEFAULT_DIALOGUE_AI_BENEFITS_RISKS_LLM_MODERATED_REPORT_PATH
)
DEFAULT_DIALOGUE_AI_BENEFITS_RISKS_LLM_MODERATED_SSE_PATH = (
    _config.DEFAULT_DIALOGUE_AI_BENEFITS_RISKS_LLM_MODERATED_SSE_PATH
)
DEFAULT_PURE_DIALOGUE_ROBUSTNESS_MATRIX_BROWSER_REPORT_PATH = (
    _config.DEFAULT_PURE_DIALOGUE_ROBUSTNESS_MATRIX_BROWSER_REPORT_PATH
)
DEFAULT_PURE_DIALOGUE_ROBUSTNESS_MATRIX_REPORT_PATH = (
    _config.DEFAULT_PURE_DIALOGUE_ROBUSTNESS_MATRIX_REPORT_PATH
)
DEFAULT_PURE_DIALOGUE_ROBUSTNESS_MATRIX_SSE_PATH = (
    _config.DEFAULT_PURE_DIALOGUE_ROBUSTNESS_MATRIX_SSE_PATH
)
DEFAULT_GROUP_PROCESS_DATA_ANALYSIS_REPORT_PATH = (
    _config.DEFAULT_GROUP_PROCESS_DATA_ANALYSIS_REPORT_PATH
)
DEFAULT_GROUP_PROCESS_DATA_ANALYSIS_SSE_PATH = (
    _config.DEFAULT_GROUP_PROCESS_DATA_ANALYSIS_SSE_PATH
)
DEFAULT_GROUP_PROCESS_DOCUMENT_STRATEGY_REPORT_PATH = (
    _config.DEFAULT_GROUP_PROCESS_DOCUMENT_STRATEGY_REPORT_PATH
)
DEFAULT_GROUP_PROCESS_DOCUMENT_STRATEGY_SSE_PATH = (
    _config.DEFAULT_GROUP_PROCESS_DOCUMENT_STRATEGY_SSE_PATH
)
DEFAULT_GROUP_PROCESS_FAILURE_READABLE_REPORT_PATH = (
    _config.DEFAULT_GROUP_PROCESS_FAILURE_READABLE_REPORT_PATH
)
DEFAULT_GROUP_PROCESS_FAILURE_READABLE_SSE_PATH = (
    _config.DEFAULT_GROUP_PROCESS_FAILURE_READABLE_SSE_PATH
)
DEFAULT_GROUP_PROCESS_FRONTEND_PREVIEW_BROWSER_REPORT_PATH = (
    _config.DEFAULT_GROUP_PROCESS_FRONTEND_PREVIEW_BROWSER_REPORT_PATH
)
DEFAULT_GROUP_PROCESS_FRONTEND_PREVIEW_REPORT_PATH = (
    _config.DEFAULT_GROUP_PROCESS_FRONTEND_PREVIEW_REPORT_PATH
)
DEFAULT_GROUP_PROCESS_FRONTEND_PREVIEW_SSE_PATH = (
    _config.DEFAULT_GROUP_PROCESS_FRONTEND_PREVIEW_SSE_PATH
)
DEFAULT_GROUP_PROCESS_WORKFLOW_DELIVERY_REPORT_PATH = (
    _config.DEFAULT_GROUP_PROCESS_WORKFLOW_DELIVERY_REPORT_PATH
)
DEFAULT_GROUP_PROCESS_WORKFLOW_DELIVERY_SSE_PATH = (
    _config.DEFAULT_GROUP_PROCESS_WORKFLOW_DELIVERY_SSE_PATH
)
DEFAULT_P1_AGENT_CAPABILITY_PROFILE_REPORT_PATH = (
    _config.DEFAULT_P1_AGENT_CAPABILITY_PROFILE_REPORT_PATH
)
DEFAULT_P1_AGENT_CAPABILITY_PROFILE_SSE_PATH = (
    _config.DEFAULT_P1_AGENT_CAPABILITY_PROFILE_SSE_PATH
)
DEFAULT_P1_ATTRIBUTION_REPORT_PATH = _config.DEFAULT_P1_ATTRIBUTION_REPORT_PATH
DEFAULT_P1_ATTRIBUTION_SSE_PATH = _config.DEFAULT_P1_ATTRIBUTION_SSE_PATH
DEFAULT_P1_EVALUATION_REPAIR_REPORT_PATH = _config.DEFAULT_P1_EVALUATION_REPAIR_REPORT_PATH
DEFAULT_P1_EVALUATION_REPAIR_SSE_PATH = _config.DEFAULT_P1_EVALUATION_REPAIR_SSE_PATH
DEFAULT_P1_REVIEW_THREAD_REPORT_PATH = _config.DEFAULT_P1_REVIEW_THREAD_REPORT_PATH
DEFAULT_P1_REVIEW_THREAD_SSE_PATH = _config.DEFAULT_P1_REVIEW_THREAD_SSE_PATH
DEFAULT_P1_RICH_ARTIFACTS_REPORT_PATH = _config.DEFAULT_P1_RICH_ARTIFACTS_REPORT_PATH
DEFAULT_P1_RICH_ARTIFACTS_SSE_PATH = _config.DEFAULT_P1_RICH_ARTIFACTS_SSE_PATH
DEFAULT_P1_WORKFLOW_REPORT_PATH = _config.DEFAULT_P1_WORKFLOW_REPORT_PATH
DEFAULT_P1_WORKFLOW_RUNTIME_REPORT_PATH = _config.DEFAULT_P1_WORKFLOW_RUNTIME_REPORT_PATH
DEFAULT_P1_WORKFLOW_RUNTIME_SSE_PATH = _config.DEFAULT_P1_WORKFLOW_RUNTIME_SSE_PATH
DEFAULT_P1_WORKFLOW_SSE_PATH = _config.DEFAULT_P1_WORKFLOW_SSE_PATH
DEFAULT_P2_AGENT_CAPABILITY_PROFILE_V2_REPORT_PATH = (
    _config.DEFAULT_P2_AGENT_CAPABILITY_PROFILE_V2_REPORT_PATH
)
DEFAULT_P2_AGENT_CAPABILITY_PROFILE_V2_SSE_PATH = (
    _config.DEFAULT_P2_AGENT_CAPABILITY_PROFILE_V2_SSE_PATH
)
DEFAULT_QUALITY_BROWSER_REPORT_PATH = _config.DEFAULT_QUALITY_BROWSER_REPORT_PATH
DEFAULT_QUALITY_REPORT_PATH = _config.DEFAULT_QUALITY_REPORT_PATH
DEFAULT_QUALITY_SSE_PATH = _config.DEFAULT_QUALITY_SSE_PATH
E2ESettings = _config.E2ESettings
load_settings = _config.load_settings

__all__ = [
    "AGENT_IDS",
    "AGENT_FALLBACK_MATRIX_PROMPT",
    "COMMAND_FULFILLMENT_PROMPT",
    "CUSTOM_AGENT_READER_REVIEW_REPAIR_PROMPT",
    "CUSTOM_AGENT_TOOLS_PROMPT",
    "CYBERPUNK_QUALITY_PROMPT",
    "CYBERPUNK_QUALITY_V2_PROMPT",
    "DIALOGUE_AI_BENEFITS_RISKS_LLM_MODERATED_PROMPT",
    "DEFAULT_CUSTOM_AGENT_READER_REVIEW_REPAIR_BROWSER_REPORT_PATH",
    "DEFAULT_CUSTOM_AGENT_READER_REVIEW_REPAIR_REPORT_PATH",
    "DEFAULT_CUSTOM_AGENT_READER_REVIEW_REPAIR_SSE_PATH",
    "DEFAULT_CYBERPUNK_QUALITY_BROWSER_REPORT_PATH",
    "DEFAULT_CYBERPUNK_QUALITY_REPORT_PATH",
    "DEFAULT_CYBERPUNK_QUALITY_SSE_PATH",
    "DEFAULT_CYBERPUNK_QUALITY_V2_BROWSER_REPORT_PATH",
    "DEFAULT_CYBERPUNK_QUALITY_V2_REPORT_PATH",
    "DEFAULT_CYBERPUNK_QUALITY_V2_SSE_PATH",
    "DEFAULT_GROUP_CHAT_ATTRIBUTION_PROCESS_MATRIX_BROWSER_REPORT_PATH",
    "DEFAULT_GROUP_CHAT_ATTRIBUTION_PROCESS_MATRIX_REPORT_PATH",
    "DEFAULT_GROUP_CHAT_ATTRIBUTION_PROCESS_MATRIX_SSE_PATH",
    "DEFAULT_GROUP_MEMBER_FALLBACK_REPAIR_VISIBILITY_BROWSER_REPORT_PATH",
    "DEFAULT_GROUP_MEMBER_FALLBACK_REPAIR_VISIBILITY_REPORT_PATH",
    "DEFAULT_GROUP_MEMBER_FALLBACK_REPAIR_VISIBILITY_SSE_PATH",
    "DEFAULT_IM_CONTEXT_PIN_FOLLOWUP_REPAIR_BROWSER_REPORT_PATH",
    "DEFAULT_IM_CONTEXT_PIN_FOLLOWUP_REPAIR_REPORT_PATH",
    "DEFAULT_IM_CONTEXT_PIN_FOLLOWUP_REPAIR_SSE_PATH",
    "DEFAULT_IM_DIALOGUE_NO_ARTIFACT_TURN_TAKING_V2_BROWSER_REPORT_PATH",
    "DEFAULT_IM_DIALOGUE_NO_ARTIFACT_TURN_TAKING_V2_REPORT_PATH",
    "DEFAULT_IM_DIALOGUE_NO_ARTIFACT_TURN_TAKING_V2_SSE_PATH",
    "DEFAULT_DIALOGUE_AI_BENEFITS_RISKS_LLM_MODERATED_BROWSER_REPORT_PATH",
    "DEFAULT_DIALOGUE_AI_BENEFITS_RISKS_LLM_MODERATED_REPORT_PATH",
    "DEFAULT_DIALOGUE_AI_BENEFITS_RISKS_LLM_MODERATED_SSE_PATH",
    "DEFAULT_PURE_DIALOGUE_ROBUSTNESS_MATRIX_BROWSER_REPORT_PATH",
    "DEFAULT_PURE_DIALOGUE_ROBUSTNESS_MATRIX_REPORT_PATH",
    "DEFAULT_PURE_DIALOGUE_ROBUSTNESS_MATRIX_SSE_PATH",
    "DEFAULT_STATIC_PACKAGE_DEPLOY_REPAIR_MATRIX_BROWSER_REPORT_PATH",
    "DEFAULT_STATIC_PACKAGE_DEPLOY_REPAIR_MATRIX_REPORT_PATH",
    "DEFAULT_STATIC_PACKAGE_DEPLOY_REPAIR_MATRIX_SSE_PATH",
    "DEFAULT_COMMAND_FULFILLMENT_BROWSER_REPORT_PATH",
    "DEFAULT_COMMAND_FULFILLMENT_REPORT_PATH",
    "DEFAULT_COMMAND_FULFILLMENT_SSE_PATH",
    "DEFAULT_CONTEXT_FOLLOWUP_BROWSER_REPORT_PATH",
    "DEFAULT_CONTEXT_FOLLOWUP_REPORT_PATH",
    "DEFAULT_CONTEXT_FOLLOWUP_SSE_PATH",
    "DEFAULT_PRESENTATION_MARKERS_BROWSER_REPORT_PATH",
    "DEFAULT_PRESENTATION_MARKERS_REPORT_PATH",
    "DEFAULT_PRESENTATION_MARKERS_SSE_PATH",
    "DEFAULT_TASK_MANAGER_PARALLEL_BROWSER_REPORT_PATH",
    "DEFAULT_TASK_MANAGER_PARALLEL_REPORT_PATH",
    "DEFAULT_TASK_MANAGER_PARALLEL_SSE_PATH",
    "DEFAULT_TASK_MANAGER_PARALLEL_V2_BROWSER_REPORT_PATH",
    "DEFAULT_TASK_MANAGER_PARALLEL_V2_REPORT_PATH",
    "DEFAULT_TASK_MANAGER_PARALLEL_V2_SSE_PATH",
    "DEFAULT_GROUP_DIALOGUE_DEBATE_REPORT_PATH",
    "DEFAULT_GROUP_DIALOGUE_DEBATE_SSE_PATH",
    "DEPLOYMENT_PROMPT",
    "DEPLOYMENT_REPAIR_PROMPT",
    "E2ESettings",
    "FULLSTACK_PROMPT",
    "GROUP_CHAT_ATTRIBUTION_PROCESS_MATRIX_PROMPT",
    "GROUP_MEMBER_FALLBACK_REPAIR_VISIBILITY_PROMPT",
    "GROUP_PROCESS_DATA_ANALYSIS_PROMPT",
    "GROUP_PROCESS_DOCUMENT_STRATEGY_PROMPT",
    "GROUP_PROCESS_FAILURE_READABLE_PROMPT",
    "GROUP_PROCESS_WORKFLOW_DELIVERY_PROMPT",
    "GROUP_DIALOGUE_DEBATE_PROMPT",
    "IM_CONTEXT_PIN_FOLLOWUP_REPAIR_PROMPT",
    "ONE_CLICK_CONTAINER_DEPLOY_REPAIR_PROMPT",
    "P1_AGENT_CAPABILITY_PROFILE_AGENT_IDS",
    "P1_AGENT_CAPABILITY_PROFILE_PROMPT",
    "P1_AGENT_CAPABILITY_PROFILE_SEED_PROMPT",
    "P1_ATTRIBUTION_PROMPT",
    "P1_EVALUATION_REPAIR_PROMPT",
    "P1_REVIEW_THREAD_PROMPT",
    "P1_RICH_ARTIFACTS_PROMPT",
    "P1_WORKFLOW_PROMPT",
    "P1_WORKFLOW_RUNTIME_PROMPT",
    "P2_AGENT_CAPABILITY_PROFILE_V2_PROMPT",
    "PRESENTATION_COLLAPSE_PROMPT",
    "PURE_DIALOGUE_ROBUSTNESS_MATRIX_PROMPT",
    "SCENARIOS",
    "SERVER_COMMAND_RE",
    "ScenarioSpec",
    "STATIC_PACKAGE_DEPLOY_REPAIR_MATRIX_PROMPT",
    "TASK_MANAGER_PARALLEL_PROMPT",
    "TASK_MANAGER_PARALLEL_V2_PROMPT",
    "evaluate_p1_agent_capability_profile",
    "evaluate_p1_evaluation_repair",
    "evaluate_p1_rich_artifacts",
    "evaluate_p2_agent_capability_profile_v2",
    "get_scenario",
    "load_settings",
    "main",
]


if __name__ == "__main__":
    main()
