/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                409: components["responses"]["Conflict"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List conversations */
        get: {
            parameters: {
                query?: {
                    archived?: boolean;
                    pinned_only?: boolean;
                    search?: string;
                    page?: number;
                    page_size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConversationList"];
                    };
                };
            };
        };
        put?: never;
        /** Create conversation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateConversationRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Conversation"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get conversation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Conversation"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete conversation */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update conversation */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateConversationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Conversation"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/conversations/{id}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get compressed conversation memory
         * @description Development-only endpoint for B1 memory debugging.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConversationMemory"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/orchestrator-runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * List Orchestrator structured runs
         * @description Development-only endpoint for Orchestrator memory debugging.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrchestratorRunList"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/orchestrator-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                run_id: string;
            };
            cookie?: never;
        };
        /**
         * Get Orchestrator structured run detail
         * @description Development-only endpoint for Orchestrator memory debugging.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    run_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrchestratorRunDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/context-compression/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get context compression config
         * @description Returns active summarizer settings without exposing API keys.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContextCompressionConfig"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update context compression config
         * @description Development-only runtime update for compression model settings.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateContextCompressionConfigRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContextCompressionConfig"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/api/v1/context-compression/config/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test context compression config
         * @description Development-only connection test for a compression model config.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ContextCompressionTestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContextCompressionTestResult"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** List messages in conversation */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                    direction?: "before" | "after";
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageList"];
                    };
                };
            };
        };
        put?: never;
        /** Send message */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendMessageRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SendMessageResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete message */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update message (Pin / Unpin) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateMessageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/messages/{id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate agent message */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * SSE stream for agent response
         * @description 服务端推送事件流。事件类型见 docs/api-spec.md § 5。
         *     客户端应使用 fetch-event-source 库（支持自定义 Header）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{conversation_id}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        /** Get workspace file tree */
        get: {
            parameters: {
                query?: {
                    max_depth?: number;
                };
                header?: never;
                path: {
                    conversation_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceTreeResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{conversation_id}/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                path: string;
            };
            cookie?: never;
        };
        /** Read workspace file */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversation_id: string;
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File content */
                200: {
                    headers: {
                        "X-Content-Type-Options"?: string;
                        /** @description Present for text/html responses. */
                        "Content-Security-Policy"?: string;
                        /** @description Present for text/html responses. */
                        "X-Frame-Options"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                        "text/plain": string;
                        "text/html": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description File too large */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /** Write workspace file */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversation_id: string;
                    path: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/octet-stream": string;
                    "text/plain": string;
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description File too large */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{conversation_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        /** Get workspace preview status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversation_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Preview session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspacePreviewResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Start or reuse workspace static preview */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversation_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkspacePreviewRequest"];
                };
            };
            responses: {
                /** @description Preview session */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspacePreviewResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Preview start failed */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /** Stop workspace preview */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversation_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stopped preview session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspacePreviewResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{conversation_id}/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        /** List workspace deployments */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversation_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deployment records */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceDeploymentListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Create a workspace deployment or source export */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversation_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkspaceDeploymentRequest"];
                };
            };
            responses: {
                /** @description Deployment record */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceDeploymentResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Deployment failed */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{conversation_id}/deployments/{deployment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                deployment_id: string;
            };
            cookie?: never;
        };
        /** Get workspace deployment status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversation_id: string;
                    deployment_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deployment record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceDeploymentResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Stop a workspace deployment or delete its source export */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversation_id: string;
                    deployment_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stopped deployment record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkspaceDeploymentResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{conversation_id}/deployments/{deployment_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                deployment_id: string;
            };
            cookie?: never;
        };
        /** Download a workspace source export */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    conversation_id: string;
                    deployment_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Source zip archive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/zip": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agents */
        get: {
            parameters: {
                query?: {
                    builtin?: boolean;
                    provider?: components["schemas"]["AgentProvider"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentList"];
                    };
                };
            };
        };
        put?: never;
        /** Create agent */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAgentRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Agent"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get agent */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Agent"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete agent */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update agent */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAgentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Agent"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @example RESOURCE_NOT_FOUND */
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        OffsetPagination: {
            items: unknown[];
            total: number;
            page: number;
            page_size: number;
        };
        CursorPagination: {
            items: unknown[];
            next_cursor?: string | null;
            has_more: boolean;
        };
        TextBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            text: string;
        };
        CodeBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "code";
            language: string;
            code: string;
        };
        DiffBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "diff";
            filename: string;
            before: string;
            after: string;
        };
        WebPreviewBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "web_preview";
            /** Format: uri */
            url: string;
            title?: string | null;
            description?: string | null;
            thumbnail_url?: string | null;
        };
        FileBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "file";
            filename: string;
            /** Format: uri */
            url: string;
            size: number;
            mime_type: string;
        };
        DeploymentStatusBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "deployment_status";
            deployment_id: string;
            /** @enum {string} */
            kind: "static_site" | "source_zip" | "container";
            /** @enum {string} */
            status: "publishing" | "published" | "failed" | "stopped" | "not_supported";
            title?: string | null;
            url?: string | null;
            download_url?: string | null;
            error?: string | null;
            logs_preview?: string | null;
            size_bytes?: number | null;
        };
        ToolCallBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool_call";
            call_id: string;
            tool_name: string;
            arguments: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            status: "pending" | "ok" | "error";
            output_preview?: string | null;
            output_truncated?: boolean | null;
            error_code?: string | null;
        };
        ContentBlock: components["schemas"]["TextBlock"] | components["schemas"]["CodeBlock"] | components["schemas"]["DiffBlock"] | components["schemas"]["WebPreviewBlock"] | components["schemas"]["FileBlock"] | components["schemas"]["DeploymentStatusBlock"] | components["schemas"]["ToolCallBlock"];
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            avatar_url?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        RegisterRequest: {
            username: string;
            password: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        AuthResponse: {
            access_token: string;
            /** @enum {string} */
            token_type: "bearer";
            /** @description seconds */
            expires_in: number;
            user: components["schemas"]["User"];
        };
        /** @enum {string} */
        ConversationMode: "single" | "group";
        Conversation: {
            /** Format: uuid */
            id: string;
            title: string;
            mode: components["schemas"]["ConversationMode"];
            agent_ids: string[];
            is_pinned: boolean;
            is_archived: boolean;
            /** Format: date-time */
            last_message_at: string;
            last_message_preview?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        CreateConversationRequest: {
            title: string;
            mode: components["schemas"]["ConversationMode"];
            agent_ids: string[];
        };
        UpdateConversationRequest: {
            title?: string;
            is_pinned?: boolean;
            is_archived?: boolean;
        };
        ConversationList: components["schemas"]["OffsetPagination"] & {
            items?: components["schemas"]["Conversation"][];
        };
        ConversationMemory: {
            /** Format: uuid */
            conversation_id: string;
            summary_text: string;
            /** Format: uuid */
            summarized_until_message_id?: string | null;
            source_message_count: number;
            source_token_estimate: number;
            summary_token_estimate: number;
            /** @example rules-v1 */
            algorithm_version: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OrchestratorRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversation_id: string;
            /** Format: uuid */
            agent_message_id?: string | null;
            /** Format: uuid */
            user_message_id?: string | null;
            /** @enum {string} */
            status: "running" | "done" | "error" | "cancelled";
            user_request: string;
            plan_source: string;
            final_summary: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            completed_at?: string | null;
        };
        OrchestratorTask: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            task_id: string;
            agent_id: string;
            title: string;
            instruction: string;
            depends_on: string[];
            priority: number;
            expected_output?: string | null;
            include_history: boolean;
            final_state: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OrchestratorTaskAttempt: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            /** Format: uuid */
            task_row_id: string;
            task_id: string;
            attempt_index: number;
            agent_id: string;
            state: string;
            text_preview: string;
            tool_summaries: string[];
            artifact_paths: string[];
            missing_artifact_paths: string[];
            error?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at?: string | null;
        };
        OrchestratorRunEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            run_id: string;
            event_type: string;
            task_id?: string | null;
            agent_id?: string | null;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        OrchestratorRunList: {
            items: components["schemas"]["OrchestratorRun"][];
            total: number;
        };
        OrchestratorRunDetail: {
            run: components["schemas"]["OrchestratorRun"];
            tasks: components["schemas"]["OrchestratorTask"][];
            attempts: components["schemas"]["OrchestratorTaskAttempt"][];
            events: components["schemas"]["OrchestratorRunEvent"][];
        };
        ContextCompressionConfig: {
            /** @enum {string} */
            mode: "hybrid" | "rules";
            /** @enum {string} */
            provider: "deepseek" | "openai" | "openai_compatible" | "anthropic";
            /** @example deepseek-v4-flash */
            model: string;
            /** @example 1200 */
            summary_max_tokens: number;
            /** @example 12 */
            recent_raw_keep: number;
            api_key_configured: boolean;
            /** @enum {string} */
            api_key_source: "context_compression_api_key" | "missing";
            /** @example sk-***f0cb */
            api_key_preview?: string | null;
            /** @example https://api.deepseek.com */
            base_url: string;
            supported_models: string[];
        };
        UpdateContextCompressionConfigRequest: {
            /** @enum {string} */
            mode?: "hybrid" | "rules";
            /** @enum {string} */
            provider?: "deepseek" | "openai" | "openai_compatible" | "anthropic" | "claude";
            /** @example deepseek-v4-flash */
            model?: string;
            api_key?: string;
            /** @example https://api.deepseek.com */
            base_url?: string;
            summary_max_tokens?: number;
            recent_raw_keep?: number;
        };
        ContextCompressionTestRequest: {
            /** @enum {string} */
            provider?: "deepseek" | "openai" | "openai_compatible" | "anthropic" | "claude";
            /** @example deepseek-v4-flash */
            model?: string;
            api_key?: string;
            /** @example https://api.deepseek.com */
            base_url?: string;
        };
        ContextCompressionTestResult: {
            ok: boolean;
            provider: string;
            model: string;
            error_code?: string | null;
            message?: string | null;
        };
        /** @enum {string} */
        MessageRole: "user" | "agent" | "system";
        /** @enum {string} */
        MessageStatus: "pending" | "streaming" | "done" | "error";
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversation_id: string;
            role: components["schemas"]["MessageRole"];
            agent_id?: string | null;
            content: components["schemas"]["ContentBlock"][];
            /** Format: uuid */
            reply_to_id?: string | null;
            status: components["schemas"]["MessageStatus"];
            /** @default false */
            is_pinned: boolean;
            /** Format: date-time */
            created_at: string;
        };
        SendMessageRequest: {
            content: components["schemas"]["ContentBlock"][];
            /** @description 群聊时指定目标 Agent；单聊可省略 */
            target_agent_id?: string | null;
        };
        SendMessageResponse: {
            user_message: components["schemas"]["Message"];
            agent_message: components["schemas"]["Message"];
        };
        UpdateMessageRequest: {
            is_pinned?: boolean;
        };
        MessageList: components["schemas"]["CursorPagination"] & {
            items?: components["schemas"]["Message"][];
        };
        /** @enum {string} */
        AgentProvider: "claude_code" | "codex" | "opencode" | "builtin" | "mock" | "claude" | "deepseek" | "openai" | "custom";
        /** @enum {string} */
        CreatableAgentProvider: "claude_code" | "codex" | "opencode" | "builtin";
        AgentConfig: {
            /**
             * @description ModelGateway backend for builtin agents.
             * @enum {string}
             */
            model_backend?: "claude" | "deepseek" | "openai";
            /**
             * @description ModelGateway backend for orchestrator direct answers.
             * @enum {string}
             */
            answer_model_backend?: "claude" | "deepseek" | "openai";
            /**
             * @description ModelGateway backend for orchestrator LLM planning.
             * @enum {string}
             */
            planner_model_backend?: "claude" | "deepseek" | "openai";
            /**
             * @description Whether Orchestrator uses LLM planning for task decomposition.
             * @default true
             */
            llm_planning: boolean;
            /** @description Whether planner failures may fall back to legacy template tasks. */
            planner_fallback_to_template?: boolean;
            /** @description Model parameters shared by orchestrator planner/replanner. */
            orchestrator_llm_config?: {
                [key: string]: unknown;
            };
            max_iterations?: number;
            /** @description Whether builtin orchestrator uses ReAct dynamic task graph execution. */
            react_enabled?: boolean;
            /** @description Whether ReAct step/action/observation summaries are visible in chat output. */
            react_trace_visible?: boolean;
            react_decision_max_tokens?: number;
            mcp_servers?: {
                [key: string]: unknown;
            }[];
            command?: string | string[];
            args?: string[];
            timeout_seconds?: number;
            max_runtime_seconds?: number;
            idle_timeout_seconds?: number;
            heartbeat_interval_seconds?: number;
            /** @description Whether external runtime agents may answer pure Q&A through ModelGateway without starting SDK/CLI. */
            qa_short_circuit_enabled?: boolean;
            /**
             * @description ModelGateway backend for external direct chat.
             * @enum {string}
             */
            qa_model_backend?: "claude" | "deepseek" | "openai";
            qa_model?: string | null;
            qa_classifier_model?: string | null;
            qa_max_tokens?: number;
            qa_classifier_max_tokens?: number;
            qa_temperature?: number;
            qa_request_timeout_seconds?: number;
            /** @description Optional per-task fallback agents for orchestrator retries. */
            task_fallback_agent_ids?: string[];
            max_task_attempts?: number;
            task_result_context_max_chars?: number;
            task_result_item_max_chars?: number;
            /** @description Whether Orchestrator writes and injects structured run memory. */
            orchestrator_memory_enabled?: boolean;
            orchestrator_memory_recent_runs?: number;
            orchestrator_memory_context_max_chars?: number;
            /** @description Whether Orchestrator uses native tool calling for ordinary task requests. */
            orchestrator_tool_calling_enabled?: boolean;
            /** @description Whether Orchestrator native tool_call/tool_result events are visible in chat output. */
            orchestrator_tool_trace_visible?: boolean;
            orchestrator_tool_max_iterations?: number;
            orchestrator_tool_result_max_chars?: number;
            orchestrator_tool_read_max_bytes?: number;
            /**
             * @description Whether Orchestrator may execute independent DAG tasks concurrently.
             * @default true
             */
            orchestrator_parallel_enabled: boolean;
            /** @default 3 */
            orchestrator_parallel_max_concurrency: number;
            /**
             * @description Whether Orchestrator runs artifact evaluation and reflection.
             * @default true
             */
            orchestrator_evaluation_enabled: boolean;
            /** @default 65536 */
            orchestrator_evaluation_read_max_bytes: number;
            /**
             * @description Whether Orchestrator may run allowlisted deterministic test evaluators.
             * @default false
             */
            orchestrator_test_runner_enabled: boolean;
            /**
             * @description Allowlisted test evaluator aliases, such as python_compile_artifacts.
             * @default []
             */
            orchestrator_test_command_allowlist: Array<string>;
        } & {
            [key: string]: unknown;
        };
        Agent: {
            id: string;
            name: string;
            provider: components["schemas"]["AgentProvider"];
            avatar_url: string;
            capabilities: string[];
            system_prompt?: string | null;
            config: components["schemas"]["AgentConfig"];
            is_builtin: boolean;
            /** Format: date-time */
            created_at: string;
        };
        CreateAgentRequest: {
            name: string;
            provider: components["schemas"]["CreatableAgentProvider"];
            /** @default  */
            avatar_url: string;
            /** @default [] */
            capabilities: string[];
            system_prompt?: string | null;
            config: components["schemas"]["AgentConfig"];
        };
        UpdateAgentRequest: {
            name?: string;
            avatar_url?: string;
            capabilities?: string[];
            system_prompt?: string | null;
            config?: components["schemas"]["AgentConfig"];
        };
        AgentList: components["schemas"]["OffsetPagination"] & {
            items?: components["schemas"]["Agent"][];
        };
        WorkspaceTreeNode: {
            name: string;
            /** @description Path relative to workspace root */
            path: string;
            /** @enum {string} */
            type: "directory" | "file";
            children?: components["schemas"]["WorkspaceTreeNode"][];
            size?: number | null;
            mime_type?: string | null;
        };
        WorkspaceTreeResponse: {
            /** @example /workspaces/00000000-0000-0000-0000-000000000000 */
            root: string;
            tree: components["schemas"]["WorkspaceTreeNode"];
        };
        WorkspacePreviewRequest: {
            entry_path: string;
            /**
             * @default static
             * @enum {string}
             */
            mode: "static";
            requested_port?: number | null;
        };
        WorkspacePreviewResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversation_id: string;
            /** Format: uuid */
            workspace_id: string;
            entry_path: string;
            /** @enum {string} */
            mode: "static";
            port: number;
            pid?: number | null;
            url: string;
            /** @enum {string} */
            status: "starting" | "running" | "stopped" | "error";
            error?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            last_accessed_at: string;
        };
        WorkspaceDeploymentRequest: {
            /** @enum {string} */
            kind: "static_site" | "source_zip" | "container";
            entry_path?: string | null;
            requested_port?: number | null;
        };
        WorkspaceDeploymentResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversation_id: string;
            /** Format: uuid */
            workspace_id: string;
            /** @enum {string} */
            kind: "static_site" | "source_zip" | "container";
            /** @enum {string} */
            status: "publishing" | "published" | "failed" | "stopped" | "not_supported";
            entry_path?: string | null;
            url?: string | null;
            download_url?: string | null;
            error?: string | null;
            logs: string[];
            size_bytes?: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        WorkspaceDeploymentListResponse: {
            items: components["schemas"]["WorkspaceDeploymentResponse"][];
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
